# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Tony Bui's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Tony Nguyen Bui
headline: Mechanical Engineering
description: >- # dont remove this line. this will ignore all new lines until the next section
  A fellow grease monkey with a bachelor's in Mechanical Engineering from Stanford University.<br>
  <br>
  I love to tackle the most interesting design challenges of our time, well-grounded in physics, math, manufacturing, and
  ethical considerations. My engineering strategy is informed by the Stanford School of Design, which emphasizes rapid iteration, interdisciplinary
  collaboration, manufacturability/scalability, and a human-centered design.<br>
  <br>
  Throughout my 4 years of undergraduate education, I had the opportunity to intern as a Mechanical Design Engineer for Tesla
  Motors' Power Electronics team, "wear many hats" as a mechanical engineering/product management intern for Trucklabs (now Conmet,
  a trucking tech startup with its flagship, tractor-mounted, aerodynamic product), design an aerodynamic wind deflector for my convertible
  car (2005 Mazda Miata) to reduce cabin turbulence when top-down driving, fabricated pneumatic actuated soft-robotics with infinite degrees
  of freedom, CNC milled a bespoke Aluminum case for my double-edged safety razor, designed and fabricated a low-cost/locally-manufacturable
  tilt-in-space wheelchair for Tanzanians with severe postural disabilities (for Senior Capstone), and many more fun, impactful projects<br>
  <br>
  This is just the beginning! I aim to leverage my education and experience as a stepping-stone to high-impact engineering.<br>
# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume file.pdf} or add external link such as pdf saved in google drive 
resume-url: https://drive.google.com/file/d/1KLvCEokXfPf8RlIonTi8eGBogjRsvfwb/view?usp=sharing


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: tonybui7    # https://www.linkedin.com/in/{tonybui7} 
  github: tonybui7.github.io    # https://github.com/{your url slug} 
  stackoverflow:      # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: 3D Modeling
    tools:
    - Fusion 360 (Autodesk, CAD/CAM)
    - Solidworks (Dassault Systèmes)
    - CATIA 3DX (Dassault Systèmes)
    - MATLAB (Mathworks)
    - Ansys Electronics Desktop (Maxwell, Mechanical, Icepak, HFSS, Thermal)
    - Abaqus (Dassault Systèmes)
  - category: Prototyping / Fabrication / DfM
    tools:
    - 3-Axis CNC
    - Additive 3D Printing (FDM, SLA, Latticing)
    - Manual Mill, Lathe, Drill Press
    - Laser Cutting
    - WaterJet
    - Metal Forming (Sheet Metal, Tube Bending, Oxy-Acetylene Welding)
    - Metal Casting (Sand Casting, Die Casting)
    - Arduino
  - category: Engineering Skills and Practices
    tools:
    - Geometric Dimensioning and Tolerancing (GD&T)
    - ISO fits and tolerances
  - category: PCB Design
    tools:
    - Altium Designer
    - Altium
    - Eagle 
    - KiCad
  - category: Problem Solving / Risk Management
    tools:
    - Root Cause Analysis (e.g., 5 Whys, Fishbone Diagram)
    - DFMEA / PFMEA 
    - Six Sigma methodologies
    - Shain Red-X


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   https://formspree.io/f/{8-digit key}



# Active theme (Update this to switch themes). Make sure to keep the indentation the same.
colors: # this is the basic theme
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"
  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
